- 
  name: Apache Installation
  hosts: Ansible-Client
  tasks:
  - yum:
      name: httpd
      state: present
  - service:
      name: httpd
      state: started
      enabled: yes
  - name: Ensure httpd service added to firewalld
    firewalld:
           service: httpd
           state: enabled
           permanent: yes
           immediate: yes
  - name: Ensure port 80 added to firewalld
    firewalld:
            port: 80/tcp
            state: enabled
            permanent: yes
            immediate: yes
    
